### ISSUE TITLE
302 object moved response not supported

### ISSUE THREAD

**Issue by claytonneal** [sdstoehr/har-reader#1]
Hiya,
If i get http status "302 object moved" in the HAR file then i get an error reading it with this library:

de.sstoehr.harreader.HarReaderException: com.fasterxml.jackson.databind.JsonMappingException: Unknown HttpStatus: Object moved. (through reference chain: de.sstoehr.harreader.model.Har["log"]->de.sstoehr.harreader.model.HarLog["entries"]->de.sstoehr.harreader.model.HarEntry["response"]->de.sstoehr.harreader.model.HarResponse["statusText"])

Can this be supported please as its a blocker for me.
Thanks

**Comment by sdstoehr** [comment]
This should be working in Version 1.0.1, which I released just now. It may take some time until it is available in Maven Central Repository.

Best regards,
Sebastian

**Comment by allancq17** [comment]
I have the same problem reading the file when it gets a "NO RESPONSE" for an object with the status -999.

de.sstoehr.harreader.HarReaderException: com.fasterxml.jackson.databind.JsonMappingException: Unknown HttpStatus: -999. (through reference chain: de.sstoehr.harreader.model.Har["log"]->de.sstoehr.harreader.model.HarLog["entries"]->java.util.ArrayList[91]->de.sstoehr.harreader.model.HarEntry["response"]->de.sstoehr.harreader.model.HarResponse["status"])

![error](https://cloud.githubusercontent.com/assets/2170888/6903272/5e84ab9c-d6d6-11e4-8e67-e6920de5e3cf.png)

Can you please support it?, this is the only missing thing for my script to work properly.

Thanks!

**Comment by sdstoehr** [comment]
Fixed in issue #3
