### ISSUE TITLE
Unsupported method CCM_POST

### ISSUE THREAD

**Issue by kazimiru** [sdstoehr/har-reader#13]
Hey guys,
i'm trying to parse HAR log from ROKU device and there is unsupported method exception.

`Can not construct instance of de.sstoehr.harreader.model.HttpMethod from String value 'CCM_POST': value not one of declared Enum instance names: [GET, POST, PUT, HEAD, PROPFIND, OPTIONS, REPORT, DELETE, CONNECT, TRACE]`

Google says it's kind of Microsoft's auth feature or something... 

Can you add it to Enum?

Thanks!

**Comment by sdstoehr** [comment]
Sorry, that you had to wait so long for a reply. I was really busy and had no time to work on my GitHub projects.

Version 2.0.2 should be available at Maven Central repository in the following hours.

Best,
Sebastian
