### ISSUE TITLE
Missing equals and hashcode method in HarEntry

### ISSUE THREAD

**Issue by thibaut-sticky** [sdstoehr/har-reader#15]
Hi, I want to thank you for this library. It's really useful with Browsermob proxy.
I met a strange behavior with the following snipped code.
```Java
Har har1 = harReader.readFromString(jsonObject.toString());
Har har2 = harReader.readFromString(jsonObject.toString());
assertTrue(har1.getLog().getEntries().equals(har2.getLog().getEntries()))
```
I expect this test to pass. But because there is not equals and hashcode methods in the HarEntry class, the test failed. If a PR is done for this purpose, would you accept it?

**Comment by sdstoehr** [comment]
Thanks for your feedback! I've added the missing hashCode and equals methods in version 2.0.3

It should be available in Maven Central within some hours.

Best,
Sebastian

**Comment by thibaut-sticky** [comment]
Whoa it was pretty fast. Thanks a lot. I saw you added also the associated test. Perfect 👍
