### ISSUE TITLE
NO RESPONSE not supported

### ISSUE THREAD

**Issue by allancq17** [sdstoehr/har-reader#3]
Hi,

I'm getting an error reading the HAR file when it gets a "NO RESPONSE" for an object with the status -999.

de.sstoehr.harreader.HarReaderException: com.fasterxml.jackson.databind.JsonMappingException: Unknown HttpStatus: -999. (through reference chain: de.sstoehr.harreader.model.Har["log"]->de.sstoehr.harreader.model.HarLog["entries"]->java.util.ArrayList[91]->de.sstoehr.harreader.model.HarEntry["response"]->de.sstoehr.harreader.model.HarResponse["status"])

Can you please support it?, this is the only missing thing for my script to work properly.

Thanks!

![error](https://cloud.githubusercontent.com/assets/2170888/7006691/52f1bd46-dc40-11e4-8000-700c7b8ba583.png)

**Comment by sdstoehr** [comment]
I changed the behaviour of the HAR reader: Now it supports every HTTP status code (even when it is no real HTTP status code like "-999" [(List of status codes)]). All unknown status codes are mapped to the enum value "UNKNOWN_HTTP_STATUS".

Regards,
Sebastian

[(List of status codes)]: http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

**Comment by allancq17** [comment]
Thanks a lot!
