### ISSUE TITLE
Error while reading HAR file

### ISSUE THREAD

**Issue by sunnysachdeva** [sdstoehr/har-reader#5]
while reading a HAr file I am getting below error

 Can not construct instance of de.sstoehr.harreader.model.HttpMethod from String value 'HEAD': value not one of declared Enum instance names: [GET, POST, PUT]

I am attaching the screenshot of all the calls.
![harread_issue](https://cloud.githubusercontent.com/assets/5293359/7343204/19d76900-ecdc-11e4-950a-b3d6ff7b085f.png)

Pls let me know if there is any workaround for it

**Comment by sunnysachdeva** [comment]
Thanks for fixing this.
Please let me know when will it be ported to maven central repository

Regards,

Sunny Sachdeva


Date: Mon, 27 Apr 2015 00:41:51 -0700

**Comment by sdstoehr** [comment]
The new version 1.0.7 should be synced to Maven Central by now.

Regards,
Sebastian
